import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#eef2ff" },
  top: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 10,
  },
  title: { fontSize: 20, fontWeight: "900" },
  stageWrap: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
    position: "relative",
  },
  loadingBox: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  stageResponder: { flex: 1 },
  stageTransform: { flex: 1 },
  actions: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    flexDirection: "row",
    gap: 10,
  },
  actionBtn: {
    flex: 1,
    backgroundColor: "#6d28d9",
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
  },
  actionBtnDisabled: {
    opacity: 0.5,
  },
  actionText: { color: "white", fontWeight: "900", fontSize: 16 },
  secondaryBtn: {
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryText: { fontWeight: "900", opacity: 0.85 },
  hidden: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
    left: -1000,
    top: -1000,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    width: "100%",
    borderRadius: 18,
    backgroundColor: "#fff",
    padding: 16,
    gap: 12,
    elevation: 6,
  },
  modalTitle: { fontSize: 18, fontWeight: "900" },
  modalInput: {
    minHeight: 90,
    borderRadius: 14,
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontWeight: "800",
    textAlignVertical: "top",
  },
  modalRow: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "flex-end",
  },
  modalBtn: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 90,
  },
  modalCancel: {
    backgroundColor: "#f1f5f9",
  },
  modalOk: {
    backgroundColor: "#6d28d9",
  },
  modalCancelText: { fontWeight: "900", opacity: 0.85 },
  modalOkText: { fontWeight: "900", color: "white" },
  modalHint: { opacity: 0.65, fontWeight: "700" },
  secondaryBtnDisabled: {
    opacity: 0.5,
  },
});
