import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#eef2ff" },
  top: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 10,
  },
  title: { fontSize: 20, fontWeight: "900" },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  emptyIcon: { fontSize: 64, opacity: 0.3 },
  emptyText: { fontSize: 18, fontWeight: "800", opacity: 0.5 },
  stageWrap: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
  },
  imageContainer: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "#fff",
    overflow: "hidden",
    position: "relative",
  },
  imageContainerExport: {
    backgroundColor: "transparent",
    borderRadius: 0,
  },
  captureView: {
    flex: 1,
    backgroundColor: "transparent",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  imageHidden: { opacity: 0 },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  loadingText: {
    opacity: 0.75,
    fontWeight: "800",
    color: "white",
  },
  overlayBox: {
    position: "absolute",
    backgroundColor: "transparent",
  },
  stageTransform: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  hiddenExportContainer: {
    position: "absolute",
    left: -10000,
    top: -10000,
    opacity: 0,
  },
  exportView: {
    backgroundColor: "#ffffff",
    position: "relative",
  },
  actions: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    flexDirection: "row",
    gap: 10,
  },
  actionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#6d28d9",
    paddingVertical: 14,
    borderRadius: 16,
    elevation: 2,
  },
  actionBtnDisabled: {
    opacity: 0.5,
  },
  actionText: { color: "white", fontWeight: "900", fontSize: 14 },
  sigBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(124,58,237,0.35)",
  },
  sigBtnText: {
    color: "#6d28d9",
    fontWeight: "900",
    fontSize: 14,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    width: "100%",
    borderRadius: 18,
    backgroundColor: "#fff",
    padding: 16,
    gap: 12,
    elevation: 6,
  },
  modalTitle: { fontSize: 18, fontWeight: "900" },
  modalInput: {
    minHeight: 90,
    borderRadius: 14,
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontWeight: "800",
    textAlignVertical: "top",
  },
  modalRow: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "flex-end",
  },
  modalBtn: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 90,
  },
  modalCancel: {
    backgroundColor: "#f1f5f9",
  },
  modalOk: {
    backgroundColor: "#6d28d9",
  },
  modalCancelText: { fontWeight: "900", opacity: 0.85 },
  modalOkText: { fontWeight: "900", color: "white" },
  modalHint: { opacity: 0.65, fontWeight: "700" },
  exportLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  exportLoadingCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 32,
    alignItems: "center",
    gap: 16,
    minWidth: 200,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  exportLoadingSpinner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#f3f4f6",
    alignItems: "center",
    justifyContent: "center",
  },
  exportLoadingText: {
    fontSize: 18,
    fontWeight: "900",
    color: "#1f2937",
  },
  exportLoadingHint: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6b7280",
  },
});
