import { I18nManager, StyleSheet } from "react-native";
import { theme } from "../../ui/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.colors.appBg },
  container: {
    flex: 1,
    paddingHorizontal: theme.spacing.pagePadding,
    paddingTop: 14,
    gap: 16,
  },
  header: {
    alignItems: "center",
    gap: 6,
    paddingTop: 4,
  },
  headerRow: {
    width: "100%",
    alignItems: "flex-end",
  },
  appTitle: {
    ...theme.typography.h1,
    color: theme.colors.textPrimary,
    fontSize: 28,
  },
  langIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: theme.colors.cardBorder,
    backgroundColor: theme.colors.cardBg,
    alignItems: "center",
    justifyContent: "center",
    ...theme.shadow.card,
  },
  langIconText: { fontSize: 18 },
  tabs: {
    flexDirection: "row",
    backgroundColor: theme.colors.cardBg,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.colors.cardBorder,
    padding: 4,
    ...theme.shadow.card,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnActive: {
    backgroundColor: theme.colors.brandSoft,
    borderWidth: 1,
    borderColor: "rgba(109, 40, 217, 0.25)",
  },
  tabText: { fontWeight: "800", color: theme.colors.textSecondary },
  tabTextActive: { color: theme.colors.textPrimary },
  card: {
    backgroundColor: theme.colors.cardBg,
    borderRadius: theme.radius.xl,
    borderWidth: 1,
    borderColor: theme.colors.cardBorder,
    padding: 16,
    gap: 12,
    ...theme.shadow.card,
  },
  formTitle: { fontSize: 18, fontWeight: "900", color: "#0f172a" },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.cardBorder,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#fff",
    fontWeight: "700",
  },
  passwordInput: {
    textAlign: I18nManager.isRTL ? "right" : "left",
    writingDirection: I18nManager.isRTL ? "rtl" : "ltr",
  },
  forgotPasswordBtn: {
    alignSelf: I18nManager.isRTL ? "flex-end" : "flex-start",
    paddingVertical: 2,
    paddingHorizontal: 2,
    marginTop: -4,
  },
  forgotPasswordText: {
    color: theme.colors.brand,
    fontWeight: "800",
    textDecorationLine: "underline",
  },
  forgotPasswordHint: {
    marginTop: -2,
    marginBottom: 2,
    color: theme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
    textAlign: "left",
  },
  forgotPasswordHintRtl: {
    textAlign: "right",
  },
  errorText: {
    color: "#b91c1c",
    fontWeight: "700",
  },
  legalRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(37, 99, 235, 0.18)",
    backgroundColor: "rgba(37, 99, 235, 0.06)",
  },
  legalCheckbox: {
    width: 21,
    height: 21,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#94a3b8",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
  },
  legalCheckboxChecked: {
    backgroundColor: theme.colors.brand,
    borderColor: theme.colors.brand,
  },
  legalCheckboxError: {
    borderColor: "#dc2626",
  },
  legalCheckboxMark: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "900",
  },
  legalText: {
    flex: 1,
    color: theme.colors.textSecondary,
    lineHeight: 11,
    fontWeight: "600",
    fontSize: 7,
  },
  legalLink: {
    color: theme.colors.brand,
    textDecorationLine: "underline",
    fontWeight: "800",
  },
  legalHint: {
    marginTop: -2,
    marginBottom: 2,
    fontSize: 13,
    fontWeight: "700",
  },
  legalHintWarning: {
    color: "#9a3412",
  },
  legalHintAccepted: {
    color: "#166534",
  },
  primaryBtn: {
    backgroundColor: theme.colors.buttonPrimary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  primaryBtnDisabled: { opacity: 0.6 },
  primaryBtnText: { color: "white", fontWeight: "900", fontSize: 16 },
  btnRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  orRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginVertical: 4,
  },
  orLine: { flex: 1, height: 1, backgroundColor: "#e5e7eb" },
  orText: { color: theme.colors.textSecondary, fontWeight: "700" },
  googleBtn: {
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.12)",
  },
  googleBtnDisabled: { opacity: 0.6 },
  guestBtn: {
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(37, 99, 235, 0.25)",
    backgroundColor: "rgba(37, 99, 235, 0.08)",
  },
  guestBtnText: { fontWeight: "800", color: theme.colors.brand },
  langBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    padding: 16,
  },
  langCard: {
    backgroundColor: "white",
    borderRadius: 18,
    padding: 16,
  },
  langTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: theme.colors.textPrimary,
    textAlign: "right",
  },
  langRow: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.10)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  langRowActive: {
    borderColor: theme.colors.brand,
    backgroundColor: "rgba(37, 99, 235, 0.06)",
  },
  langRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  langRowIcon: { fontSize: 18 },
  langRowText: {
    fontWeight: "800",
    color: theme.colors.textPrimary,
  },
  langCheck: {
    fontWeight: "900",
    color: theme.colors.brand,
  },
});
